TTS.Web/Controllers/HesapController.cs
using TTS.BLL;
using System.Web.Mvc;
using TTS.DAL;

namespace TTS.Web.Controllers
{
    public class HesapController : Controller
    {
        public ActionResult Login(string errorMessage = null)
        {
            ViewBag.SisteminAdi = "Tedavi Takip Sistemi";
            ViewBag.ErrorMessage = Session["ErrorMessage"] != null ? Session["ErrorMessage"] : "";
            return View();
        }

        [HttpPost]
        public ActionResult Login(Kullanici model)
        {
            ViewBag.SisteminAdi = "Tedavi Takip Sistemi";
            using (HesapServisi hesapServisi = new HesapServisi())
            {
                Kullanici kullanici;
                kullanici = hesapServisi.DoktorGirisYap(model.tc_no, model.parola);

                if (kullanici == null)
                    kullanici = hesapServisi.HemsireGirisYap(model.tc_no, model.parola);

                if (kullanici == null)
                    kullanici = hesapServisi.GorevliGirisYap(model.tc_no, model.parola);

                if (kullanici != null)
                {
                    Session["Kullanici"] = kullanici;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.ErrorMessage = "Lütfen geçerli bir kullanıcı bilgisi giriniz.";
                    return View(model);
                }
            }
        }
        public ActionResult Profilim()
        {
            Session["Baslik"] = "Kullanıcı Bilgileri";
            Kullanici kullanici = Session["Kullanici"] as Kullanici;
            return View(kullanici);
        }
        [HttpPost]
        public ActionResult Profilim(int id, string old_password, string new_password)
        {
            using (HesapServisi hesapServisi = new HesapServisi())
            {
                Kullanici kullanici = hesapServisi.KullaniciAl(id);
                if (kullanici.parola == old_password)
                {

                    if (kullanici is doktorlar)
                    {
                        using (DoktorServisi Servis = new DoktorServisi())
                        {
                            doktorlar doktor = kullanici as doktorlar;
                            doktor.parola = new_password;
                            Servis.Duzenle(doktor);

                        }
                    }
                    if (kullanici is hemsireler)
                    {
                        using (HemsireServisi Servis = new HemsireServisi())
                        {
                            hemsireler hemsire = kullanici as hemsireler;
                            hemsire.parola = new_password;
                            Servis.Duzenle(hemsire);

                        }
                    }
                    if (kullanici is gorevliler)
                    {
                        using (GorevliServisi Servis = new GorevliServisi())
                        {
                            gorevliler gorevli = kullanici as gorevliler;
                            gorevli.parola = new_password;
                            Servis.Duzenle(gorevli);

                        }
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Lütfen geçerli bir parola giriniz.";
                }
                return View(kullanici);
            }
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }




    }
}

TTS.Web/Controllers/IlacYonetimiController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TTS.DAL;

namespace TTS.Web.Controllers
{
    public class IlacYonetimiController : TemelController
    {
        private TTSEntities db = new TTSEntities();

		private string SinifAdi(){
			var displayName = typeof(ilaclar)
				.GetCustomAttributes(typeof(DisplayNameAttribute), true)
				.FirstOrDefault() as DisplayNameAttribute;

			if (displayName != null)
				return displayName.DisplayName;
			else
				return "Kayıt";
		}

		public ActionResult Index()	
        {			
            Session["Baslik"] =  SinifAdi() + " Listesi";
			return View(db.ilaclar.Where(e=>e.aktif_mi).ToList());
        }
		public ActionResult Details(int? id)	
        {
            Session["Baslik"] =  SinifAdi() + " Detay Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			ilaclar ilaclar = db.ilaclar.Find(id);
            if (ilaclar == null)
            {
                return HttpNotFound();
            }
            return View(ilaclar);
        }
        public ActionResult Create()
        {
            Session["Baslik"] =  SinifAdi() + " Oluşturma Ekranı";
            return View();
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,adi,doz_sayisi,birim,aktif_mi")] ilaclar ilaclar)

        {
			ilaclar.aktif_mi = true;
            if (ModelState.IsValid)
            {
                db.ilaclar.Add(ilaclar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ilaclar);
        }
        public ActionResult Edit(int? id)
        {
            Session["Baslik"] =  SinifAdi() + " Düzenleme Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ilaclar ilaclar = db.ilaclar.Find(id);

            if (ilaclar == null)
            {
                return HttpNotFound();
            }
            return View(ilaclar);
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,adi,doz_sayisi,birim,aktif_mi")] ilaclar ilaclar)

        {
			ilaclar.aktif_mi = true;
            if (ModelState.IsValid)
            {
                db.Entry(ilaclar).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(ilaclar);
        }

        public ActionResult Delete(int? id)
        {
            Session["Baslik"] =  SinifAdi() + " Silme Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ilaclar ilaclar = db.ilaclar.Find(id);

            if (ilaclar == null)
            {
                return HttpNotFound();
            }
            return View(ilaclar);
        }

        public ActionResult DeleteConfirmed(int id)

        {
            ilaclar ilaclar = db.ilaclar.Find(id);            
            db.Entry(ilaclar).State = EntityState.Modified;
            ilaclar.aktif_mi = false;            
			db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TTS.Web/Controllers/OdaYonetimiController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TTS.BLL;
using TTS.DAL;

namespace TTS.Web.Controllers
{
    public class OdaYonetimiController : TemelController
    {
        private TTSEntities db = new TTSEntities();

		private string SinifAdi(){
			var displayName = typeof(odalar)
				.GetCustomAttributes(typeof(DisplayNameAttribute), true)
				.FirstOrDefault() as DisplayNameAttribute;

			if (displayName != null)
				return displayName.DisplayName;
			else
				return "Kayıt";
		}

		public ActionResult Index()	
        {			
            Session["Baslik"] =  SinifAdi() + " Listesi";
            if (db.odalar.Count() == 0)
                Helper.OdalariDagit();
            var odalar = db.odalar.Include(o => o.bolumler).Include(o => o.hastalar);
			return View(odalar.Where(e=>e.aktif_mi).ToList());
        }
		public ActionResult Details(int? id)	
        {
            Session["Baslik"] =  SinifAdi() + " Detay Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			odalar odalar = db.odalar.Find(id);
            if (odalar == null)
            {
                return HttpNotFound();
            }
            return View(odalar);
        }
        public ActionResult Tahsis(int id, int bolum_id)
        {
            Session["Baslik"] =  SinifAdi() + " Tahsis Ekranı";
            Session["HastaId"] = id;
            return View(db.odalar.Where(o=>o.bolum_id == bolum_id));
        }
        public ActionResult TahsisEt(int id)
        {
            int hasta_id = (int)Session["HastaId"];
            using (HastaServisi Servis = new HastaServisi())
            {
                hastalar hasta = Servis.TekGetir(hasta_id);
                hasta.oda_id = id;
                Servis.Duzenle(hasta);
            }
            odalar oda = db.odalar.Find(id);

            using (BLL.HastaIslemServisi Servis = new BLL.HastaIslemServisi())
            {
                hastanin_islemleri islem = new hastanin_islemleri();
                islem.aciklama = string.Format("Hastanın yatış işlemi gerçekleştirildi. Hasta, {0} kliniğindeki {1} numaralı odaya yatırıldı.", oda.bolumler.adi, oda.oda_no);
                islem.aktif_mi = true;
                islem.hasta_id = (int)Session["HastaId"];
                islem.gorevli_id = OAnkiKullanici.id;
                islem.islem_id = 5;
                islem.islem_zamani = DateTime.Now;
                Servis.Ekle(islem);
            }
            return RedirectToAction("Details", "HastaYonetimi", new { id = (int)Session["HastaId"] }); ;
        }
        public ActionResult Bosalt(int id)
        {
            using (BLL.HastaServisi Servis = new BLL.HastaServisi())
            {
                hastalar hasta = Servis.TekGetir(id);
                hasta.oda_id = null;
                Servis.Duzenle(hasta);
            }
            using (BLL.HastaIslemServisi Servis = new BLL.HastaIslemServisi())
            {
                hastanin_islemleri islem = new hastanin_islemleri();
                islem.aciklama = "Hastanın çıkışı yapıldı.";
                islem.aktif_mi = true;
                islem.hasta_id = id;
                islem.gorevli_id = OAnkiKullanici.id;
                islem.islem_id = 8;
                islem.islem_zamani = DateTime.Now;
                Servis.Ekle(islem);
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult BaskaHastayeGonder()
        {
            using (BLL.HastaIslemServisi Servis = new BLL.HastaIslemServisi())
            {
                hastanin_islemleri islem = new hastanin_islemleri();
                islem.aciklama = "Bölümde boş oda olmadığından hasta, başka hastaneye sevk edildi.";
                islem.aktif_mi = true;
                islem.hasta_id = (int)Session["HastaId"];
                islem.gorevli_id = OAnkiKullanici.id;
                islem.islem_id = 6;
                islem.islem_zamani = DateTime.Now;
                Servis.Ekle(islem);
            }
            return RedirectToAction("Details", "HastaYonetimi", new { id = (int)Session["HastaId"] }); 
        }
        public ActionResult Create()
        {
            Session["Baslik"] =  SinifAdi() + " Oluşturma Ekranı";
            ViewBag.bolum_id = db.bolumler.Select(b => new SelectListItem
            {
                Text = b.adi,
                Value = b.id.ToString()
            });
            return View();
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,bolum_id,oda_no,hasta_kapasitesi,aktif_mi")] odalar odalar)

        {
			odalar.aktif_mi = true;
            if (ModelState.IsValid)
            {
                db.odalar.Add(odalar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.bolum_id = db.bolumler.Select(b => new SelectListItem
            {
                Text = b.adi,
                Value = b.id.ToString()
            });
            return View(odalar);
        }
        public ActionResult Edit(int? id)
        {
            Session["Baslik"] =  SinifAdi() + " Düzenleme Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odalar odalar = db.odalar.Find(id);

            if (odalar == null)
            {
                return HttpNotFound();
            }
            ViewBag.bolum_id = Helper.GetSelectListItems(db.bolumler.ToList());
            return View(odalar);
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,bolum_id,oda_no,hasta_kapasitesi,aktif_mi")] odalar odalar)

        {
			odalar.aktif_mi = true;
            if (ModelState.IsValid)
            {
                db.Entry(odalar).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.bolum_id = Helper.GetSelectListItems(db.bolumler.ToList());
            return View(odalar);
        }

        public ActionResult Delete(int? id)
        {
            Session["Baslik"] =  SinifAdi() + " Silme Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odalar odalar = db.odalar.Find(id);

            if (odalar == null)
            {
                return HttpNotFound();
            }
            return View(odalar);
        }
        public ActionResult DeleteConfirmed(int id)

        {
            odalar odalar = db.odalar.Find(id);            
            db.Entry(odalar).State = EntityState.Modified;
            odalar.aktif_mi = false;            
			db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TTS.Web/Views/Shared/PleaseWait.cshtml
<h1>Bekleyin</h1>

TTS.Web/Views/Shared/_AddUpdateModal.cshtml
@model TTS.Web.Models.DataModel
@{
    string id = Model.Action == TTS.Web.Models.Action.Create ? "create-modal" : "edit-modal";
    string controller = Model.Type.Name + "Management";
    string action = Model.Action == TTS.Web.Models.Action.Create ? "Create" : "Edit";
}
<div class="modal fade" id="@id">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm(action, controller))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" class="name-id" name="id" />
                <input type="hidden" name="aktif_mi" value="true" />
                <!-- Modal Header -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">@Model.Title</h4>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    @foreach (System.Reflection.PropertyInfo property in Model.Type.GetProperties().Where(p => !p.Name.Equals("id") && !p.Name.Equals("aktif_mi")))
                    {
                        bool skipProperty = property.GetGetMethod().IsVirtual;
                        if (skipProperty)
                        {
                            continue;
                        }
                        string cls = Model.Action == TTS.Web.Models.Action.Create ? "form-control" : "form-control name-" + property.PropertyName;

                        <div class="form-group">
                            <div class="row">
                                <div class="col-xs-4">
                                    <label>@property.GetDisplayName()</label>&nbsp;
                                    @if (property.IsRequired())
                                    {
                                        <span style="color:red">*</span>
                                    }
                                </div>
                                <div class="col-xs-8">
                                    <input name="@property.PropertyName" id="@property.PropertyName" type="@property.PropertyType.InputType()" class="form-control" required />
                                </div>

                            </div>
                        </div>
                    }
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Vazgeç</button>
                    <button type="submit" class="btn btn-success">KAYDET</button>
                </div>
            }
        </div>
    </div>
</div>

TTS.Web/Views/Shared/_GorevliAnaEkran.cshtml
@model gorevliler
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <h3 class="headline">Yatış Verilen Hastalar</h3>
        </div>
        <div class="box-body">
            <table class="table index-table">
                <thead>
                    <tr>
                        <th>
                            TC No
                        </th>
                        <th>
                            Adı Soyadı
                        </th>
                        <th>
                            Giriş Tarihi
                        </th>
                        <th>
                            Bölümü
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @using (HastaServisi Servis = new HastaServisi())
                    {

                        foreach (hastalar hasta in Servis.TumunuGetir())
                        {
                            var islemler = hasta.hastanin_islemleri.ToList();
                            var son_islem = islemler.Last();
                            if (islemler.Count != 0 && son_islem.islem_id == 4)
                            {
                                <tr>
                                    <td>
                                        @hasta.tc_no
                                    </td>
                                    <td>
                                        @hasta.adi @hasta.soyadi
                                    </td>
                                    <td>
                                        @hasta.hastanin_islemleri.ToList()[0].islem_zamani.ToString("dd.MM.yyyy, HH:mm")
                                    </td>
                                    <td>
                                        @hasta.hemsireler.bolumler.adi
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs" role="group">
                                            <a href="@Url.Action("Tahsis","OdaYonetimi",new { id=hasta.id, bolum_id = hasta.hemsireler.bolum_id})" class="btn btn-default" data-toggle="tooltip" title="Oda Tahsis Et">
                                                <i class="fas fa-door-open"></i>&nbsp;Oda Tahsis Et
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <h3 class="headline">Yatan Hastalar</h3>
        </div>
        <div class="box-body">
            <table class="table index-table">
                <thead>
                    <tr>
                        <th>
                            TC No
                        </th>
                        <th>
                            Adı Soyadı
                        </th>
                        <th>
                            Giriş Tarihi
                        </th>
                        <th>
                            Bölümü
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @using (HastaServisi Servis = new HastaServisi())
                    {
                        foreach (hastalar hasta in Servis.TumunuGetir())
                        {
                            var islemler = hasta.hastanin_islemleri.ToList();
                            var son_islem = islemler.Last();
                            if (islemler.Count != 0 && son_islem.islem_id == 5)
                            {
                                <tr>
                                    <td>
                                        @hasta.tc_no
                                    </td>
                                    <td>
                                        @hasta.adi @hasta.soyadi
                                    </td>
                                    <td>
                                        @hasta.hastanin_islemleri.ToList()[0].islem_zamani.ToString("dd.MM.yyyy, HH:mm")
                                    </td>
                                    <td>
                                        @hasta.hemsireler.bolumler.adi
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs" role="group">
                                            <a href="@Url.Action("Details","HastaYonetimi",new { id=hasta.id })" class="btn btn-default" data-toggle="tooltip" title="Hasta Ekranı">
                                                <i class="fas fa-info-circle"></i>&nbsp;Detaylar
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <h3 class="headline">Taburcu Edilen Hastalar</h3>
        </div>
        <div class="box-body">
            <table class="table index-table">
                <thead>
                    <tr>
                        <th>
                            TC No
                        </th>
                        <th>
                            Adı Soyadı
                        </th>
                        <th>
                            Giriş Tarihi
                        </th>
                        <th>
                            Bölümü
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @using (HastaServisi Servis = new HastaServisi())
                    {
                        foreach (hastalar hasta in Servis.TumunuGetir())
                        {
                            var islemler = hasta.hastanin_islemleri.ToList();
                            var son_islem = islemler.Last();
                            if (islemler.Count != 0 && son_islem.islem_id == 7)
                            {
                                <tr>
                                    <td>
                                        @hasta.tc_no
                                    </td>
                                    <td>
                                        @hasta.adi @hasta.soyadi
                                    </td>
                                    <td>
                                        @hasta.hastanin_islemleri.ToList()[0].islem_zamani.ToString("dd.MM.yyyy, HH:mm")
                                    </td>
                                    <td>
                                        @hasta.hemsireler.bolumler.adi
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs" role="group">
                                            <a href="@Url.Action("Bosalt","OdaYonetimi",new { id=hasta.id })" class="btn btn-default" data-toggle="tooltip" title="Odayı Boşalt">
                                                <i class="fas fa-sign-out"></i>&nbsp;Odayı Boşalt
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            }

                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

TTS.Web/Views/Shared/_Sidebar.cshtml
@{
    Kullanici kullanici = Session["Kullanici"] as Kullanici;
}
<aside class="main-sidebar" id="sidebar">
    <section class="sidebar">
        @* BEGIN Menu *@

        <ul class="sidebar-menu" data-widget="tree">
            <li>
                <a href="@Url.Action("Index","HastaYonetimi")">
                    <i class="fas fa-user-injured"></i>&nbsp;
                    <span>Hastalar</span><i class="fa fa-angle-right pull-right"></i>
                </a>
            </li>


            @if (kullanici is hemsireler)
            {
                hemsireler hemsire = kullanici as hemsireler;
                if (hemsire.bas_hemsire_mi)
                {
                    <li>
                        <a href="@Url.Action("Index","HemsireYonetimi")">
                            <i class="fas fa-user-nurse"></i>&nbsp;
                            <span>Hemşireler</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>
                }
                <li>
                    <a href="@Url.Action("Takvim","NobetYonetimi")">
                        <i class="fas fa-cloud-moon"></i>&nbsp;
                        <span>Nöbetler</span><i class="fa fa-angle-right pull-right"></i>
                    </a>
                </li>
            }
            else if (kullanici is gorevliler)
            {
                gorevliler superGorevli = kullanici as gorevliler;
                if (superGorevli.tc_no == "admin" && superGorevli.parola == "admin")
                {
                    <li class="header">
                        Süper Yönetici Menüsü
                    </li>
                    <li>
                        <a href="@Url.Action("Index","BolumYonetimi")">
                            <i class="fas fa-sitemap"></i>&nbsp;
                            <span>Bölüm Yönetimi</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>Kullanıcı Yönetimi</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index","DoktorYonetimi")">
                                    <i class="fas fa-user-md"></i>&nbsp;
                                    <span>Doktorlar</span><i class="fa fa-angle-right pull-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","HemsireYonetimi")">
                                    <i class="fas fa-user-nurse"></i>&nbsp;
                                    <span>Hemşireler</span><i class="fa fa-angle-right pull-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","GorevliYonetimi")">
                                    <i class="fas fa-users"></i>&nbsp;
                                    <span>Görevliler</span><i class="fa fa-angle-right pull-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","NobetYonetimi")">
                            <i class="fas fa-cloud-moon"></i>&nbsp;
                            <span>Nöbetler</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","IlacYonetimi")">
                            <i class="fas fa-pills"></i>&nbsp;
                            <span>İlaç Yönetimi</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","OdaYonetimi")">
                            <i class="fas fa-door-open"></i>&nbsp;
                            <span>Oda Yönetimi</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","IslemYonetimi")">
                            <i class="fas fa-syringe"></i>&nbsp;
                            <span>İşlem Yönetimi</span><i class="fa fa-angle-right pull-right"></i>
                        </a>
                    </li>

                }
            }
        </ul>
        @* END Menu *@
    </section>
</aside>