TTS.Web/Controllers/NobetYonetimiController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TTS.DAL;

namespace TTS.Web.Controllers
{
    public class NobetYonetimiController : TemelController
    {
        private TTSEntities db = new TTSEntities();

		private string SinifAdi(){
			var displayName = typeof(nobetler)
				.GetCustomAttributes(typeof(DisplayNameAttribute), true)
				.FirstOrDefault() as DisplayNameAttribute;

			if (displayName != null)
				return displayName.DisplayName;
			else
				return "Kayıt";
		}
        public ActionResult Takvim()
        {
            Session["Baslik"] = SinifAdi() + " Takvimi";
            ViewBag.hemsire_id = Helper.GetSelectListItems(db.hemsireler.Where(h => h.id != OAnkiKullanici.id).ToList());
            return View();
        }
        public JsonResult Liste(DateTime start, DateTime end)
        {
            List<TakvimModeli> liste = new List<TakvimModeli>();
            foreach (var nobet in db.nobetler.Where(n=>n.aktif_mi).Include(n => n.hemsireler).Include(n => n.hemsireler.bolumler))
            {
                liste.Add(new TakvimModeli
                {
                    id = nobet.id,
                    title = string.Format("{0} {1}\n{2}", nobet.hemsireler.adi, nobet.hemsireler.soyadi, nobet.hemsireler.bolumler.adi),
                    start = nobet.tarih.ToString("yyyy-MM-dd"),
                    end = nobet.tarih.ToString("yyyy-MM-dd")
                });
            }
            return Json(liste, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Degistir(int id,DateTime start)
        {
            nobetler nobet = db.nobetler.Find(id);
            nobet.tarih = start;
            db.Entry(nobet).State = EntityState.Modified;
            db.SaveChanges();
            string message = NobetiKontrolEt(nobet);
            return Json(new { Message = message }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index()
        {
            return RedirectToAction("Takvim");
        }
		public ActionResult Details(int? id)	
        {
            Session["Baslik"] =  SinifAdi() + " Detay Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			nobetler nobetler = db.nobetler.Find(id);
            if (nobetler == null)
            {
                return HttpNotFound();
            }
            return View(nobetler);
        }
        public ActionResult Create()
        {
            Session["Baslik"] =  SinifAdi() + " Oluşturma Ekranı";
            ViewBag.hemsire_id = Helper.GetSelectListItems(db.hemsireler.Where(h=>h.id != OAnkiKullanici.id).ToList());
            return View();
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create(string hemsire_id, string tarih)

        {
            nobetler nobetler = new nobetler();
            nobetler.hemsire_id = Convert.ToInt32(hemsire_id);
            nobetler.tarih = DateTime.ParseExact(tarih, "yyyy-MM-dd", CultureInfo.InvariantCulture);
            nobetler.aktif_mi = true;
            db.nobetler.Add(nobetler);
            db.SaveChanges();

            string message = NobetiKontrolEt(nobetler);
            return Json(new { Message = message }, JsonRequestBehavior.AllowGet);
        }

        private string NobetiKontrolEt(nobetler nobetler)
        {
            string message = "";
            foreach (nobetler nobet in db.nobetler.Where(n => n.aktif_mi && n.hemsire_id == nobetler.hemsire_id))
            {

                DateTime yarin = nobet.tarih.AddDays(1);
                if (nobetler.tarih.Ticks == yarin.Ticks)
                {
                    message = "DİKKAT! Bu hemşire bir önceki gün de nöbetçidir.\n";
                }

                DateTime dun = nobet.tarih.AddDays(-1);
                if (nobetler.tarih.Ticks == dun.Ticks)
                {
                    message += "DİKKAT! Bu hemşire bir sonraki gün de nöbetçidir.";
                }
            }

            return message;
        }

        public ActionResult Edit(int? id)
        {
            Session["Baslik"] =  SinifAdi() + " Düzenleme Ekranı";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nobetler nobetler = db.nobetler.Find(id);

            if (nobetler == null)
            {
                return HttpNotFound();
            }
            ViewBag.hemsire_id = Helper.GetSelectListItems(db.hemsireler.Where(h => h.id != OAnkiKullanici.id).ToList());
            return View(nobetler);
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,hemsire_id,tarih,aktif_mi")] nobetler nobetler)

        {
			nobetler.aktif_mi = true;
            if (ModelState.IsValid)
            {
                db.Entry(nobetler).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Takvim");
            }
            ViewBag.hemsire_id = Helper.GetSelectListItems(db.hemsireler.Where(h => h.id != OAnkiKullanici.id).ToList());
            return View(nobetler);
        }

        public ActionResult Delete(int id)
        {
            nobetler nobetler = db.nobetler.Find(id);
            db.Entry(nobetler).State = EntityState.Modified;
            nobetler.aktif_mi = false;
            db.SaveChanges();
            return RedirectToAction("Takvim");
        }

        public ActionResult DeleteConfirmed(int id)

        {
            nobetler nobetler = db.nobetler.Find(id);            
            db.Entry(nobetler).State = EntityState.Modified;
            nobetler.aktif_mi = false;            
			db.SaveChanges();
            return RedirectToAction("Takvim");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TTS.Web/Views/NobetYonetimi/Create.cshtml
@model TTS.DAL.nobetler
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row" style="padding-top:10px;">
            <div class="col-md-12">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.hemsire_id, htmlAttributes: new { @class = "control-label" })

                    @Html.DropDownList("hemsire_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.hemsire_id, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-12" style="margin-top:20px;">
                    <a href="Index" class="btn btn-default pull-left">Ana Listeye Dön</a>
                    <input type="submit" value="Kaydet" class="btn btn-primary pull-right" />
                </div>
            </div>
        </div>
    }
</div>

TTS.Web/Views/NobetYonetimi/Delete.cshtml
@model TTS.DAL.nobetler

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
	Kullanici kullanici = Session["Kullanici"] as Kullanici;
	bool superGorevliMi = false;
	if(kullanici is gorevliler)
	{
		gorevliler superGorevli = kullanici as gorevliler;
		superGorevliMi = superGorevli.tc_no == "admin"?true:false;
	}
}
<style>
    dt,dd{
        text-align:left;
    }
</style>
<div class="box">
    <div class="row" style="padding:20px;">
		<div class="col-md-12">		
			<h3>Bu kaydı silmek istediğinizden emin misiniz?</h3>
			<dl class="dl-horizontal">
								<dt>
					@Html.DisplayNameFor(model => model.tarih)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.tarih)
				</dd>
								<dt>
					@Html.DisplayNameFor(model => model.hemsireler.adi)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.hemsireler.adi)
				</dd>
					</dl>
		</div>
	</div>
	<div class="row" style="padding:20px;">
		<div class="col-md-12">
			<a href="../DeleteConfirmed/@Model.id" class="btn btn-danger pull-left">Sil</a>
			<a href="../Index" class="btn btn-primary pull-right">Ana Listeye Dön</a>
		</div>
	</div>
</div>

TTS.Web/Views/NobetYonetimi/Details.cshtml
@model TTS.DAL.nobetler

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
	Kullanici kullanici = Session["Kullanici"] as Kullanici;
	bool superGorevliMi = false;
	if(kullanici is gorevliler)
	{
		gorevliler superGorevli = kullanici as gorevliler;
		superGorevliMi = superGorevli.tc_no == "admin"?true:false;
	}
}
<style>
    dt,dd{
        text-align:left;
    }
</style>
<div class="box">
    <div class="row" style="padding:20px;">
		<div class="col-md-12">
			<dl class="dl-horizontal">
								<dt>
					@Html.DisplayNameFor(model => model.tarih)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.tarih)
				</dd>
								<dt>
					@Html.DisplayNameFor(model => model.hemsireler.adi)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.hemsireler.adi)
				</dd>
					</dl>
		</div>
	</div>
	<div class="row" style="padding:20px;">
		<div class="col-md-12">
			@if(superGorevliMi){
				<a href="../Edit/@Model.id" class="btn btn-default pull-left">Düzenle</a>
			}
			<a href="../Index" class="btn btn-primary pull-right">Ana Listeye Dön</a>
		</div>
	</div>
</div>

TTS.Web/Views/NobetYonetimi/Edit.cshtml
@model TTS.DAL.nobetler
@{
                /**/

                Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="row" style="padding-top:10px;">
            <div class="col-md-12">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.hemsire_id, htmlAttributes: new { @class = "control-label" })

                    @Html.DropDownList("hemsire_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.hemsire_id, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label" })

                    @Html.TextBoxFor(model => model.tarih, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", required = "required" })
                    @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-12" style="margin-top:20px;">
                    <a href="../Index" class="btn btn-default pull-left">Ana Listeye Dön</a>
                    <input type="submit" value="Kaydet" class="btn btn-primary pull-right" />
                </div>
            </div>
        </div>
    }
</div>

TTS.Web/Views/NobetYonetimi/Index.cshtml
@model IEnumerable<TTS.DAL.nobetler>


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Kullanici kullanici = Session["Kullanici"] as Kullanici;
    bool superGorevliMi = false;
    if (kullanici is gorevliler)
    {
        gorevliler superGorevli = kullanici as gorevliler;
        superGorevliMi = superGorevli.tc_no == "admin" ? true : false;
    }
    bool basHemsireMi = false;
    var list = Model;
    if (kullanici is hemsireler)
    {
        hemsireler basHemsire = kullanici as hemsireler;
        basHemsireMi = basHemsire.bas_hemsire_mi;
        if (!basHemsireMi)
        {
            list = Model.Where(n => n.hemsire_id == basHemsire.id);
        }
    }
}
@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="/Content/css/buttons/buttons.dataTables.min.css" />
}
<table class="table" id="index-table">
    <thead>
        <tr>
            <th>
                Nöbet Tarihi
            </th>
            <th>
                Zamanı
            </th>
            @if (basHemsireMi || superGorevliMi)
            {
                <th>
                    Bölüm
                </th>
                <th>
                    Hemşire Adı Soyadı
                </th>
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in list)
        {
            string satirSinifi = "", zamani = "";
            if (item.tarih.Day == DateTime.Now.Day && item.tarih.Month == DateTime.Now.Month && item.tarih.Year == DateTime.Now.Year)
            {
                satirSinifi = "bg-green-active";
                zamani = "BUGÜN";
            }
            else if (item.tarih.Ticks < DateTime.Now.Ticks)
            {
                satirSinifi = "bg-orange-active";
                zamani = "Eski Nöbet";
            }
            else
            {
                satirSinifi = "bg-purple-active";
                zamani = "İleri Tarihli Nöbet";
            }
            <tr class="@satirSinifi" data-toggle="tooltip" title="@zamani">
                <td>
                    @item.tarih.ToLongDateString()
                </td>
                <td>
                    @zamani
                </td>
                @if (basHemsireMi || superGorevliMi)
                {
                    <td>
                        @item.hemsireler.bolumler.ToString()
                    </td>
                    <td>
                        @item.hemsireler.ToString()
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group">
                            <a href="@Url.Action("Edit",new { id=item.id })" class="btn btn-default" data-toggle="tooltip" title="Düzenle">
                                <i class="fa fa-pencil-alt"></i>
                            </a>
                            <a href="@Url.Action("Delete",new { id=item.id })" class="btn btn-default" data-toggle="tooltip" title="Sil">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <!-- DataTables -->
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
    <script src="/Content/js/plugins/buttons/dataTables.buttons.min.js"></script>
    <script src="/Content/js/plugins/buttons/jszip.min.js"></script>
    <script src="/Content/js/plugins/buttons/pdfmake.min.js"></script>
    <script src="/Content/js/plugins/buttons/vfs_fonts.js"></script>
    <script src="/Content/js/plugins/buttons/buttons.html5.min.js"></script>
    <script src="/Content/js/plugins/buttons/buttons.print.min.js"></script>
    <script>
        $(function () {
            $('#index-table').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'dom': 'Bfrtip',
                'buttons': [
                    {
                        extend: 'print',
                        text: '<i class="fa fa-print"></i> Yazdır',
                        key: {
                            key: 'p',
                            altKey: true
                        }
                    },
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-copy"></i> Kopyala',
                        key: {
                            key: 'c',
                            altKey: true
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        text: '<i class="fa fa-file-excel"></i> Excel\'e Aktar',
                        key: {
                            key: 'x',
                            altKey: true
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        text: '<i class="fa fa-file-pdf"></i> PDF\'e Aktar',
                        key: {
                            key: 'r',
                            altKey: true
                        }
                    },
                    {
                        text: '<i class="fa fa-sync"></i> Yenile',
                        action: function () {
                            location.reload();
                        }
                    }
                ],
                "language": {
                    "sDecimal": ",",
                    "sEmptyTable": "Tabloda herhangi bir veri mevcut değil",
                    "sInfo": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
                    "sInfoEmpty": "Kayıt yok",
                    "sInfoFiltered": "(_MAX_ kayıt içerisinden bulunan)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "Sayfada _MENU_ kayıt göster",
                    "sLoadingRecords": "Yükleniyor...",
                    "sProcessing": "İşleniyor...",
                    "sSearch": "Ara:",
                    "sZeroRecords": "Eşleşen kayıt bulunamadı",
                    "oPaginate": {
                        "sFirst": "İlk",
                        "sLast": "Son",
                        "sNext": "Sonraki",
                        "sPrevious": "Önceki"
                    },
                    "oAria": {
                        "sSortAscending": ": artan sütun sıralamasını aktifleştir",
                        "sSortDescending": ": azalan sütun sıralamasını aktifleştir"
                    }
                }
            });


        })
    </script>
    @if (basHemsireMi || superGorevliMi)
    {
        <script>
        $(function () {
            $('#index-table').DataTable().button().add(0, {
                text: '<i class="fa fa-plus"></i> Yeni Ekle',
                action: function (e, dt, node, config) {
                    window.location.href = '@Url.Action("Create")';
                }
            });
        });
        </script>
    }
}

TTS.Web/Views/NobetYonetimi/Takvim.cshtml
@model TTS.DAL.nobetler

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Kullanici kullanici = Session["Kullanici"] as Kullanici;
    bool basHemsireMi = false;
    if (kullanici is hemsireler)
    {
        basHemsireMi = (kullanici as hemsireler).bas_hemsire_mi;
    }
}
@section styles{
    <!-- fullCalendar -->
    <link href="https://fullcalendar.io/releases/core/4.0.1/main.min.css" rel="stylesheet" />
    <link href="https://fullcalendar.io/releases/daygrid/4.0.1/main.min.css" rel="stylesheet" />
    <link href="https://fullcalendar.io/releases/timegrid/4.0.1/main.min.css" rel="stylesheet" />
}

<div class="row" style="padding:10px;">
    @if (basHemsireMi)
    {
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">Nöbet Ekle</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Küçült">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                @using (Html.BeginForm("Create", "NobetYonetimi"))
                {
                    <div class="row" style="padding-top:10px;">
                        <div class="col-md-12">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group col-md-5">
                                @Html.LabelFor(model => model.hemsire_id, htmlAttributes: new { @class = "control-label" })

                                @Html.DropDownList("hemsire_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.hemsire_id, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-md-5">
                                @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-md-2" style="margin-top:20px;">
                                <input type="button" value="Kaydet" class="btn btn-primary pull-right" onclick="NobetYaz()" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    <!-- /.col -->
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-body no-padding">
                <!-- THE CALENDAR -->
                <div id='calendar-container'>
                    <div id="calendar"></div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /. box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->

@section scripts{
    <script src="https://fullcalendar.io/releases/core/4.0.1/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/core/4.0.1/locales-all.js"></script>
    <script src="https://fullcalendar.io/releases/interaction/4.0.1/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/daygrid/4.0.1/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/timegrid/4.0.1/main.min.js"></script>
    <!-- Page specific script -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var Calendar = FullCalendar.Calendar;
            var Draggable = FullCalendarInteraction.Draggable;

            var containerEl = document.getElementById('external-events');
            var calendarEl = document.getElementById('calendar');

            // initialize the calendar
            // -----------------------------------------------------------------

            var calendar = new Calendar(calendarEl, {
                plugins: ['interaction', 'dayGrid', 'timeGrid'],
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                events: '@Url.Action("Liste","NobetYonetimi")',
                eventClick: function (info) {
                    if ('@basHemsireMi.ToString()' == 'True') {
                        if (confirm('Bu nöbeti silmek istiyor musunuz?')) {
                            location.href = '@Url.Action("Delete","NobetYonetimi")' + '?id=' + info.event.id;
                        }
                    }

                },
                 eventDrop: function (info) {
                     if (confirm(info.event.title + ' isimli hemşirenin nöbetini değiştirmek istiyor musunuz?')) {
                         $.get('@Url.Action("Degistir", "NobetYonetimi")' + '?id=' + info.event.id + '&start=' + info.event.start.toISOString(), function (result) {
                            if (result.Message != '') {
                                alert(result.Message);
                            }
                         });
                     } else {
                         info.revert();
                     }
                 },
            });

            calendar.setOption('locale', 'tr');
            calendar.render();
        });
        function NobetYaz() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "NobetYonetimi")' + '?hemsire_id=' + $('#hemsire_id').val() + '&tarih=' + $('#tarih').val(),
                    success: function(result) {
                        if (result.Message != '') {
                            alert(result.Message);
                        }
                    }
            });
            location.href='@Request.Url.ToString()'
        }
    </script>
}